# Generated by Django 5.2.6 on 2025-11-04 03:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rating_ratingfeedbackevent_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExperimentRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('variant_name', models.CharField(max_length=120)),
                ('executed_by', models.CharField(max_length=120)),
                ('notes', models.TextField(blank=True)),
                ('baseline_precision', models.FloatField()),
                ('variant_precision', models.FloatField()),
                ('baseline_faithfulness', models.FloatField()),
                ('variant_faithfulness', models.FloatField()),
                ('baseline_latency', models.FloatField(help_text='Latency en segundos')),
                ('variant_latency', models.FloatField(help_text='Latency en segundos')),
                ('delta_precision', models.FloatField(editable=False)),
                ('delta_faithfulness', models.FloatField(editable=False)),
                ('delta_latency', models.FloatField(editable=False)),
                ('guardrail_passed', models.BooleanField(default=True)),
                ('guardrail_reason', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='rating',
            name='issue_tag',
            field=models.CharField(choices=[('none', 'Sin etiqueta'), ('irrelevante', 'Irrelevante'), ('sin_evidencia', 'Sin evidencia'), ('tardio', 'Tardío'), ('alucinacion', 'Alucinación'), ('accion_incorrecta', 'Acción incorrecta'), ('otro', 'Otro')], default='none', max_length=32),
        ),
        migrations.AddIndex(
            model_name='rating',
            index=models.Index(fields=['issue_tag'], name='api_rating_issue_t_8f819d_idx'),
        ),
        migrations.AddIndex(
            model_name='experimentrun',
            index=models.Index(fields=['created_at'], name='api_experim_created_ec8178_idx'),
        ),
        migrations.AddIndex(
            model_name='experimentrun',
            index=models.Index(fields=['guardrail_passed'], name='api_experim_guardra_0d6475_idx'),
        ),
    ]
