# Generated by Django 5.2.7 on 2025-11-08 17:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_experimentrun_rating_issue_tag_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QueryMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_id', models.CharField(help_text='UUID de la consulta', max_length=100, unique=True)),
                ('query_text', models.TextField()),
                ('total_latency', models.FloatField(help_text='Tiempo total de respuesta en segundos')),
                ('time_to_first_token', models.FloatField(help_text='Tiempo hasta el primer token en segundos')),
                ('retrieval_time', models.FloatField(help_text='Tiempo de recuperación de documentos en segundos')),
                ('generation_time', models.FloatField(help_text='Tiempo de generación de respuesta en segundos')),
                ('is_complex_query', models.BooleanField(default=False, help_text='Si es una consulta compleja')),
                ('query_complexity_score', models.FloatField(blank=True, help_text='Score de complejidad 0-1', null=True)),
                ('documents_retrieved', models.IntegerField(help_text='Número de documentos recuperados')),
                ('top_k', models.IntegerField(default=5, help_text='Valor de K usado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.conversation')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RAGASMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evaluation_id', models.CharField(max_length=100, unique=True)),
                ('query_text', models.TextField()),
                ('response_text', models.TextField()),
                ('retrieved_contexts', models.TextField(help_text='JSON con contextos recuperados')),
                ('precision_at_k', models.FloatField(help_text='Precision@k score (0-1)')),
                ('recall_at_k', models.FloatField(help_text='Recall@k score (0-1)')),
                ('faithfulness_score', models.FloatField(help_text='Faithfulness score (0-1)')),
                ('answer_relevancy', models.FloatField(help_text='Answer relevancy score (0-1)')),
                ('context_precision', models.FloatField(blank=True, null=True)),
                ('context_recall', models.FloatField(blank=True, null=True)),
                ('hallucination_rate', models.FloatField(help_text='Tasa de alucinación (0-1)')),
                ('k_value', models.IntegerField(default=5, help_text='Valor de K usado en la evaluación')),
                ('evaluation_timestamp', models.DateTimeField(auto_now_add=True)),
                ('query_metrics', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.querymetrics')),
            ],
            options={
                'ordering': ['-evaluation_timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='querymetrics',
            index=models.Index(fields=['created_at'], name='api_queryme_created_75cdee_idx'),
        ),
        migrations.AddIndex(
            model_name='querymetrics',
            index=models.Index(fields=['is_complex_query'], name='api_queryme_is_comp_bedc3c_idx'),
        ),
        migrations.AddIndex(
            model_name='ragasmetrics',
            index=models.Index(fields=['evaluation_timestamp'], name='api_ragasme_evaluat_4b781e_idx'),
        ),
    ]
