# Generated by Django 5.2.8 on 2025-11-14 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_add_performance_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='querymetrics',
            name='api_queryme_created_total_idx',
        ),
        migrations.RemoveIndex(
            model_name='querymetrics',
            name='api_queryme_user_created_idx',
        ),
        migrations.RemoveIndex(
            model_name='querymetrics',
            name='api_queryme_query_id_idx',
        ),
        migrations.RemoveIndex(
            model_name='ragasmetrics',
            name='api_ragasme_faithfu_idx',
        ),
        migrations.RemoveIndex(
            model_name='ragasmetrics',
            name='api_ragasme_evaluat_ts_idx',
        ),
        migrations.RemoveIndex(
            model_name='ragasmetrics',
            name='api_ragasme_evaluat_idx',
        ),
        migrations.AddField(
            model_name='ragasmetrics',
            name='wer_score',
            field=models.FloatField(blank=True, help_text='Word Error Rate - menor es mejor', null=True),
        ),
        migrations.AlterField(
            model_name='ragasmetrics',
            name='answer_relevancy',
            field=models.FloatField(default=0.0, help_text='Answer relevancy score (0-1)'),
        ),
        migrations.AlterField(
            model_name='ragasmetrics',
            name='faithfulness_score',
            field=models.FloatField(default=0.0, help_text='Faithfulness score (0-1)'),
        ),
        migrations.AlterField(
            model_name='ragasmetrics',
            name='hallucination_rate',
            field=models.FloatField(default=0.0, help_text='Tasa de alucinación (0-1)'),
        ),
        migrations.AlterField(
            model_name='ragasmetrics',
            name='precision_at_k',
            field=models.FloatField(default=0.0, help_text='Precision@k score (0-1)'),
        ),
        migrations.AlterField(
            model_name='ragasmetrics',
            name='query_text',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='ragasmetrics',
            name='recall_at_k',
            field=models.FloatField(default=0.0, help_text='Recall@k score (0-1)'),
        ),
        migrations.AlterField(
            model_name='ragasmetrics',
            name='response_text',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='ragasmetrics',
            name='retrieved_contexts',
            field=models.TextField(blank=True, default='', help_text='JSON con contextos recuperados'),
        ),
    ]
