# Generated by Django 5.2.6 on 2025-11-25 03:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_add_pgvector_embeddings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('file_path', models.CharField(help_text='Ruta local del archivo', max_length=500)),
                ('file_size', models.BigIntegerField(help_text='Tamaño en bytes')),
                ('file_type', models.CharField(help_text='Extensión del archivo', max_length=50)),
                ('drive_file_id', models.CharField(blank=True, help_text='ID del archivo en Google Drive', max_length=255, null=True)),
                ('drive_uploaded', models.BooleanField(default=False, help_text='¿Se subió a Drive?')),
                ('processed', models.BooleanField(default=False, help_text='¿Se procesó para embeddings?')),
                ('chunks_created', models.IntegerField(default=0, help_text='Cantidad de chunks generados')),
                ('embeddings_generated', models.IntegerField(default=0, help_text='Cantidad de embeddings generados')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        # migrations.DeleteModel(
        #     name='EmbeddingStorage',
        # ),
        migrations.AddIndex(
            model_name='uploadeddocument',
            index=models.Index(fields=['file_name'], name='api_uploade_file_na_62e148_idx'),
        ),
        migrations.AddIndex(
            model_name='uploadeddocument',
            index=models.Index(fields=['uploaded_at'], name='api_uploade_uploade_7af994_idx'),
        ),
        migrations.AddIndex(
            model_name='uploadeddocument',
            index=models.Index(fields=['drive_file_id'], name='api_uploade_drive_f_782d2f_idx'),
        ),
    ]
