# Generated by Django 5.2.8 on 2025-11-26 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_uploadeddocument_delete_embeddingstorage_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmbeddingStorage',
        ),
    ]
