version: "3.9"

services:
  db:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_NAME:-rag_asistente}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-sistemas}
      MYSQL_USER: ${DB_USER:-root}
      MYSQL_PASSWORD: ${DB_PASSWORD:-sistemas}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    command: ["--default-authentication-plugin=mysql_native_password"]

  backend:
    build:
      context: ./backend
    restart: unless-stopped
    env_file:
      - ./backend/.env
    environment:
      DB_HOST: db
      DB_PORT: 3306
      PORT: 8000
    depends_on:
      - db
    volumes:
      - ./backend/data:/app/data
      - ./backend/chroma_db:/app/chroma_db
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./frontend
      args:
        REACT_APP_API_URL: ${REACT_APP_API_URL:-http://localhost:8000}
    restart: unless-stopped
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  db_data:
