[phases.setup]
nixPkgs = ['python313']

[phases.install]
cmds = [
    'pip install --upgrade pip',
    'pip install -r requirements.txt'
]

[phases.build]
cmds = [
    'python manage.py collectstatic --noinput'
]

[start]
cmd = 'gunicorn core.wsgi:application --bind 0.0.0.0:$PORT --workers 2 --timeout 300'
